### ISSUE TITLE
Directx games not working.

### ISSUE THREAD

**Issue by mixel1992** [jamesstringerparsec/Easy-GPU-PV#241] opened 2022-12-27 10:48 UTC
Impossible to play games that use directx. All games give errors on launch and if I try to manually install directx from the Microsoft site it crashes. I updated the video drivers by doing a clean install. Got the same OS iso I use but it doesn't work. Redid the guide at least 5 times but all the times the same result.

**Comment by Ruok2bu** [comment] 2022-12-28 14:46
I have the same problem. It does this in Windows 10 and Windows 11. The version of Easy-GPU-PV from back in January of 2022 doesnt have this problem.

**Comment by Ruok2bu** [comment] 2023-01-01 00:00
I GOT IT WORKING!

Here's what i did:

0) Do the following connected through Hyper-V and not Parsec.
1) First off get a Display Port or HDMI dongle (i have a 1080p Display Port Dongle).
2) Plug it into GPU and configure the host to only display on your primary screen and not the fake dummy screen. I did this by selecting "Show only on 1" which is next to identify button on System->Display window.
3) In task manager, delete all the startup entries that have to do with installing parsec VDD or Parsec Display Driver. If you dont, when you do the next step, it will be reinstalled.
4) Uninstall Parsec VDD.
5) In device manager, uninstall all Display Adaptors aside from your graphics card. Also uninstall all monitors.
6) Reboot.
7) The VM screen dimensions should now be using the dimensions of your dongle!

**Comment by grrminator** [comment] 2023-01-26 18:58
I dont know why but we have mentioned to the people maintaining this code that parsec virtual display is crap and they should stop using it. But because the person who maintains this works at parsec I guess they insist on using the VDD rather than a different display driver. For whatever that reason.

This repo installs the display driver every time it is not detected. You have to edit the powershell scripts to fix that.

My fork completely removes it and installs a different display driver.

https://github.com/grrminator/Easy-GPU-PV

Its essentially a direct copy without the VDD stuff. Sometimes it acts up but most if not all games work.

Games that WONT work are games that are inherently designed to hate VMs (because of cheaters).

**Comment by mixel1992** [comment] 2023-01-27 11:01
Just installed everything again with your files and still all the games that use Directx do not start.

**Comment by grrminator** [comment] 2023-01-27 14:15
Double checking release 1.6

**Comment by grrminator** [comment] 2023-01-27 14:44
For some reason, that version which I confirmed myself working before I
even released it, repeatedly, is no longer functioning. Let me investigate.
Open GL works fine which used to be the MAJOR issue. Now it looks like it
flip flopped.

**Comment by grrminator** [comment] 2023-01-27 15:32
Yea. Something happened with windows. Because all formerly working versions (I have made 6 VMs, one each version of my fork) have all ceased function.

I am not experienced enough to fix my own fork. I originally made it to just fix the virtual display stuff that THIS repo *refuses to fix* despite solutions offered in issues.

The parsec virtual display adapter interferes with running games on the VM. The issues on this repo have made it apparent. But its continuously ignored.

Im sorry. There is nothing I can do besides point you to linux which can probably do this better.

**Comment by mixel1992** [comment] 2023-01-30 15:48
installed everything again with 1.6 and set the wired display as main but still i can't install directx
[https://youtu.be/uA_Yby121zg](url)

**Comment by Kodikuu** [comment] 2023-02-15 23:17
This issue's conversation is no longer about this repository, closing.

**Closed by Kodikuu** 2023-02-15 23:17 UTC

**Comment by Ruok2bu** [comment] 2023-02-16 08:24
This issue should be fixed though, i understand the developer is biased because he works for the company. But still ... at least fix the driver so that it doesnt screw people over!

**Comment by Kupie** [comment] 2024-03-20 01:37
> This issue's conversation is no longer about this repository, closing.

Oh really? So directX is fixed in this repository? 

Thought so.
